### ISSUE TITLE
Recurring issue when Logentries goes down or isn't responsive

### ISSUE THREAD

**Issue by jrschumacher** [rapid7/logentries-monolog-handler#2]
UnexpectedValueException: Failed connecting to Logentries (110: Connection timed out) (uncaught exception) at /var/www/vendor/logentries/logentries-monolog-handler/src/Monolog/Handler/LogentriesHandler.php line 235 {"exception":"[object] (UnexpectedValueException: Failed connecting to Logentries (110: Connection timed out) at /var/www/vendor/logentries/logentries-monolog-handler/src/Monolog/Handler/LogentriesHandler.php:235)"} []

Is there someway to catch this and unbind the handler or build in a retry mechanism?

**Comment by radiumx3** [comment]
Still getting this issue, any fix ?

**Comment by rscafi** [comment]
Any progress on this? It's working with us and we are trying to find a way to limit the timeout or something like it.

**Comment by gearoidof** [comment]
I'm currently looking into this, socket timeout issues should fix in our new release v2.1

**Comment by GuilhermeGuitte** [comment]
Any news?

**Comment by vladiacob** [comment]
Any news on that issue ?

**Comment by rscafi** [comment]
> RuntimeException: Noticed exception 'RuntimeException' with message 'Failed connecting to Logentries (110: Connection timed out)' in /var/app/current/vendor/logentries/logentries-monolog-handler/src/Logentries/Socket.php:74

It hurts really bad :(
Seems to be happening more often now

**Comment by gearoidof-r7** [comment]
This project is no longer actively maintained. Leaving the issues open indicates that somebody is somehow working on it. I'll label everything as wont-fix and need-support

**Comment by vaidas-lungis** [comment]
Why not to use Monolog/LogentriesHandler?
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/LogEntriesHandler.php

**Comment by StephenHynes7** [comment]
Yeah https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/LogEntriesHandler.php would be much more diserable. Ill look to remove this project and make sure we redirect to the above.
